apiVersion: v1
kind: Service
metadata:
  labels:
    app: gitops-demo
  name: gitops-svc
spec:
  ports:
  - nodePort: 30080
    port: 9200
    protocol: TCP
    targetPort: 9200
  selector:
    app: gitops-demo
  type: NodePort
